# Generated by Django 4.1.4 on 2023-03-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('des', models.TextField(max_length=255)),
                ('price', models.FloatField(default=10.0)),
                ('product_stock', models.IntegerField(default=0)),
                ('pic', models.FileField(default='sad.jpg', upload_to='product_pics')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
