# Generated by Django 4.1.4 on 2023-03-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_namen', models.CharField(max_length=50)),
                ('price', models.FloatField(default=10.0)),
                ('pic', models.FileField(default='sad.jpg', upload_to='cart_products')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer')),
            ],
        ),
    ]
